name="ixo-feegrant-edge"
main="src/index.ts"

compatibility_date = "2022-10-12"

node_compat = true 

kv_namespaces = [ 
         { binding = "feegrantkeys", id = "d17d4ab7a91a402593555dee6d22b73e" }
]

